In [58]:
import numpy as np
import pandas as pd

In [59]:
df=pd.read_csv(r"C:\Users\HP\Downloads\Iris.csv")

In [60]:
df.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [61]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [62]:
df.shape

(150, 6)

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [64]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [65]:
df.describe(include='all')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
count,150.000000,150.000000,150.000000,150.000000,150.000000,150
unique,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,Iris-setosa
freq,NaN,NaN,NaN,NaN,NaN,50
mean,75.500000,5.843333,3.054000,3.758667,1.198667,NaN
std,43.445368,0.828066,0.433594,1.764420,0.763161,NaN
min,1.000000,4.300000,2.000000,1.000000,0.100000,NaN
25%,38.250000,5.100000,2.800000,1.600000,0.300000,NaN
50%,75.500000,5.800000,3.000000,4.350000,1.300000,NaN
75%,112.750000,6.400000,3.300000,5.100000,1.800000,NaN
max,150.000000,7.900000,4.400000,6.900000,2.500000,NaN

In [66]:
#df_drop=df.drop(columns={'Id'})
df_drop_up=df.drop('Id',axis=1)

In [67]:
df_drop_up

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [68]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [69]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [70]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [71]:
#to covert catgorical data into numerical value we have

##Label

## one hot w

###ordinal 

##target

##frequency

In [72]:
from sklearn.preprocessing import LabelEncoder

In [73]:
le=LabelEncoder()
df['Species_label_encoder']=le.fit_transform(df['Species'])

In [74]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Species_label_encoder
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0

In [75]:
df[['Species','Species_label_encoder']].value_counts()

Species          Species_label_encoder
Iris-setosa      0                        50
Iris-versicolor  1                        50
Iris-virginica   2                        50
Name: count, dtype: int64

In [76]:
#one hot encoder

df_encoded_with_pandas_dummies=pd.get_dummies(df,columns=['Species'])

In [77]:
df_encoded_with_pandas_dummies.head()#here we got false or true we change by using dtype=float

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_label_encoder,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1,5.1,3.5,1.4,0.2,0,True,False,False
1,2,4.9,3.0,1.4,0.2,0,True,False,False
2,3,4.7,3.2,1.3,0.2,0,True,False,False
3,4,4.6,3.1,1.5,0.2,0,True,False,False
4,5,5.0,3.6,1.4,0.2,0,True,False,False

In [78]:
df_encoded_with_pandas_dummies=pd.get_dummies(df,columns=['Species'],dtype=float)

In [79]:
df_encoded_with_pandas_dummies.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_label_encoder,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1,5.1,3.5,1.4,0.2,0,1.0,0.0,0.0
1,2,4.9,3.0,1.4,0.2,0,1.0,0.0,0.0
2,3,4.7,3.2,1.3,0.2,0,1.0,0.0,0.0
3,4,4.6,3.1,1.5,0.2,0,1.0,0.0,0.0
4,5,5.0,3.6,1.4,0.2,0,1.0,0.0,0.0

In [80]:
from sklearn.preprocessing import OneHotEncoder

In [81]:
encoder=OneHotEncoder(sparse_output=False)
encoded_array=encoder.fit_transform(df[['Species']])

In [82]:
encoded_array

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [83]:
encoded_df = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(['Species']))

In [84]:
encoded_df

     Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
0                    1.0                      0.0                     0.0
1                    1.0                      0.0                     0.0
2                    1.0                      0.0                     0.0
3                    1.0                      0.0                     0.0
4                    1.0                      0.0                     0.0
..                   ...                      ...                     ...
145                  0.0                      0.0                     1.0
146                  0.0                      0.0                     1.0
147                  0.0                      0.0                     1.0
148                  0.0                      0.0                     1.0
149                  0.0                      0.0                     1.0

[150 rows x 3 columns]

In [85]:
#to combine with original data fram
df_encoded_onehot=pd.concat([df,encoded_df],axis=1)

In [86]:
df_encoded_onehot

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Species_label_encoder,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0,1.0,0.0,0.0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0,1.0,0.0,0.0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0,1.0,0.0,0.0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0,1.0,0.0,0.0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,2,0.0,0.0,1.0
146,147,6.3,2.5,5.0,1.9,Iris-virginica,2,0.0,0.0,1.0
147,148,6.5,3.0,5.2,2.0,Iris-virginica,2,0.0,0.0,1.0
148,149,6.2,3.4,5.4,2.3,Iris-virginica,2,0.0,0.0,1.0
149,150,5.9,3.0,5.1,1.8,Iris-virginica,2,0.0,0.0,1.0

In [87]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Species_label_encoder
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0

In [88]:
df.drop(['Species'],axis=1,inplace=True)

In [89]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_label_encoder
0,1,5.1,3.5,1.4,0.2,0
1,2,4.9,3.0,1.4,0.2,0
2,3,4.7,3.2,1.3,0.2,0
3,4,4.6,3.1,1.5,0.2,0
4,5,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,2
146,147,6.3,2.5,5.0,1.9,2
147,148,6.5,3.0,5.2,2.0,2
148,149,6.2,3.4,5.4,2.3,2
149,150,5.9,3.0,5.1,1.8,2

In [90]:
df.drop(['Id'],axis=1,inplace=True)

In [91]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SepalLengthCm          150 non-null    float64
 1   SepalWidthCm           150 non-null    float64
 2   PetalLengthCm          150 non-null    float64
 3   PetalWidthCm           150 non-null    float64
 4   Species_label_encoder  150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [92]:
#model buliding using k mean alogrithm 

from sklearn.cluster import KMeans

#step2 intilaize and fit the model

kmeans=KMeans(n_clusters=3,random_state=42)
kmeans.fit(df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm','Species_label_encoder']]) #model is trained here

c:\Users\HP\anaconda3\envs\GenAi\Lib\site-packages\sklearn\cluster\_kmeans.py:1425: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

KMeans(n_clusters=3, random_state=42)

In [93]:
#to predict cluster
df['KMeans_cluster']=kmeans.predict(df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm','Species_label_encoder']])

In [94]:
df.head(2)

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_label_encoder,KMeans_cluster
0,5.1,3.5,1.4,0.2,0,1
1,4.9,3.0,1.4,0.2,0,1

In [95]:
df['KMeans_cluster'].value_counts()

KMeans_cluster
1    50
2    50
0    50
Name: count, dtype: int64

In [96]:
df[['Species_label_encoder','KMeans_cluster']].value_counts()

Species_label_encoder  KMeans_cluster
0                      1                 50
1                      2                 49
2                      0                 49
1                      0                  1
2                      2                  1
Name: count, dtype: int64

In [97]:
#to identify how many cluster we need we have techinques with the help of 
# these method  

#ELBOW method  and SILHOUETTE SCORE

In [102]:
import pandas as pd

dm = pd.read_excel(r"C:\Users\HP\Downloads\EXL Shared Partner Data.xlsx")
print(dm.head(2))

  Application_Nr QuoteGeneratedDate  OfferCoverageAmount Offer_Stat_Desc  \
0   CUNA11261506         2018-02-07                15000            Void
1   CUNA11263501         2018-02-08                10000          Signed

   OfferPremiumAmount OfferBillingMethod Pmnt_Freq_Desc Effective_Date  \
0               13.75        Credit Card        Monthly            NaT
1               74.80        Credit Card        Monthly     2018-02-08

  Paid_To_Date  Offered_NAP  Issued_NAP CurrentBillMethod     ProductType  \
0          NaT        165.0         NaN               NaN  SI Term Band 1
1   2022-09-08        897.6       897.6               PAC   SI Whole Life

   Age_at_AppReceived PartnerMarker
0                53.0       Liberty
1                70.0       Liberty