In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
# Suppress Warnings for clean notebook  
#It hides warning messages in your notebook output.
import warnings
warnings.filterwarnings('ignore')

In [3]:
dataset=pd.read_csv("Melbourne_housing_FULL.csv")

In [4]:
dataset.head(2)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0

In [5]:
 dataset.tail(2)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.8181,144.89351,Western Metropolitan,6543.0

In [6]:
dataset.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='str')

In [7]:
dataset.shape

(34857, 21)

In [8]:
dataset.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [9]:
#dataset.info()

In [10]:
cols_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount', 
               'Distance', 'CouncilArea', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']
dataset = dataset[cols_to_use]

In [11]:
dataset.head(2)

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,SS,Jellis,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,126.0,NaN,NaN
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,NaN,1480000.0

In [12]:
dataset.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        3
Distance             1
CouncilArea          3
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [13]:
dataset.shape

(34857, 15)

In [14]:
cols_to_fill_zero=['Propertycount','Distance','Bedroom2', 'Bathroom', 'Car']
dataset[cols_to_fill_zero]=dataset[cols_to_fill_zero].fillna(0)


dataset['Landsize']=dataset['Landsize'].fillna(dataset.Landsize.mean())
dataset['BuildingArea']=dataset['BuildingArea'].fillna(dataset.BuildingArea.mean())

In [15]:
dataset.isnull().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          3
Propertycount       0
Distance            0
CouncilArea         3
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price            7610
dtype: int64

In [16]:
dataset.dropna(inplace=True)
#Rows with any missing value are removed
#If 50% rows have missing values → you lose half dataset
#

In [17]:
dataset.shape

(27244, 15)

In [18]:
dataset.isnull().sum()

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
Price            0
dtype: int64

*****Let's one hot encode the categorical features****

In [19]:
dataset=pd.get_dummies(dataset,drop_first=True,dtype=float)

In [20]:
dataset.head(1)

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
1,2,4019.0,2.5,2.0,1.0,1.0,202.0,160.2564,1480000.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [21]:
x=dataset.drop('Price',axis=1)
y=dataset['Price']

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2)

In [23]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train,y_train)

****Let's train our Linear Regression Model on training dataset and check the accuracy on test set****

In [24]:
reg.score(x_test,y_test)

0.13853683161563934

In [25]:
reg.score(x_train,y_train)

0.6827792395792722

*****Here training score is 68% but test score is 13.85% which is very low

Normal Regression is clearly overfitting the data, 

let's try other models



Using Lasso (L1 Regularized) Regression Model*****

In [26]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=50, max_iter=100, tol=0.1)
lasso_reg.fit(x_train,y_train)
#print(lasso_reg.coef_)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [27]:
lasso_reg.score(x_test,y_test)

0.6636111369404489

In [28]:
lasso_reg.score(x_train,y_train)

0.6766985624766824

In [29]:
y_pred = lasso_reg.predict(x_test)

In [30]:
y_pred

array([1675386.13328946, 1090665.28984345,  885857.08269037, ...,
        907941.7324018 ,  792220.8275921 , 1201124.42188506],
      shape=(8174,))

In [31]:
lasso_diff=pd.DataFrame({"Actual value":y_test,"Predicated value":y_pred})
lasso_diff.head(2)

       Actual value  Predicated value
32841     1720000.0      1.675386e+06
10813      555000.0      1.090665e+06

In [32]:
lasso_diff["Error"] = lasso_diff["Actual value"] - lasso_diff["Predicated value"]
lasso_diff.head(5)

       Actual value  Predicated value          Error
32841     1720000.0      1.675386e+06   44613.866711
10813      555000.0      1.090665e+06 -535665.289843
7211       841000.0      8.858571e+05  -44857.082690
17799      415000.0      2.946947e+05  120305.305922
3397       800000.0      6.598448e+05  140155.197780

In [33]:
from sklearn import metrics
meansqerr=metrics.mean_squared_error(y_test,y_pred)
meanaberr=metrics.mean_absolute_error(y_test,y_pred)
rootsqarr=np.sqrt(metrics.mean_squared_error(y_test,y_pred))
print("r sq: {:.2f}".format(lasso_reg.score(x,y)*100))
print("mean sqaure",meansqerr)
print("mean absoulte",meanaberr)
print("root sqaure",rootsqarr)

r sq: 67.29
mean sqaure 133653603705.6428
mean absoulte 236924.54916510652
root sqaure 365586.65690317913

In [85]:
from sklearn.linear_model import Ridge
ridge_reg= Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.fit(x_train,y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [86]:
ridge_reg.score(x_test,y_test)

0.6670848945194956

In [87]:
ridge_reg.score(x_train,y_train)

0.6622376739684328