In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
# Suppress Warnings for clean notebook  
#It hides warning messages in your notebook output.
import warnings
warnings.filterwarnings('ignore')

In [3]:
dataset=pd.read_csv("Melbourne_housing_FULL.csv")

In [4]:
dataset.head(2)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0

In [5]:
dataset.tail(2)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.8181,144.89351,Western Metropolitan,6543.0

In [6]:
dataset.shape

(34857, 21)

In [7]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  str
 1   Address        34857 non-null  str
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  str
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  str
 6   SellerG        34857 non-null  str
 7   Date           34857 non-null  str
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  str
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  str
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), str(8)
memory usage: 5.6 MB

In [8]:
dataset.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [9]:
cols_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname',
               'Propertycount', 'Distance', 'CouncilArea', 'Bedroom2',
               'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']

dataset = dataset[cols_to_use]

In [10]:
dataset.head(2)

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,SS,Jellis,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,126.0,NaN,NaN
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,NaN,1480000.0

In [11]:
cols_to_fill_zero = ['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']
dataset[cols_to_fill_zero] = dataset[cols_to_fill_zero].fillna(0)

dataset['Landsize'] = dataset['Landsize'].fillna(dataset['Landsize'].mean())
dataset['BuildingArea'] = dataset['BuildingArea'].fillna(dataset['BuildingArea'].mean())

dataset.dropna(inplace=True)

In [12]:
dataset.isnull().sum()

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
Price            0
dtype: int64

In [13]:
# 5. Convert Categorical → Numerical
# =========================
dataset = pd.get_dummies(dataset, drop_first=True, dtype=float)

In [14]:
dataset.head(1)

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
1,2,4019.0,2.5,2.0,1.0,1.0,202.0,160.2564,1480000.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [15]:
# 6. Split Features & Target
# =========================
x = dataset.drop('Price', axis=1)
y = dataset['Price']

In [16]:
# 7. Train-Test Split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=2)

In [17]:
# 8. Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [18]:
#hyper tuning
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso
params = {'alpha': [0.01,0.1,1,10]}

grid = GridSearchCV(Lasso(), params, cv=5,n_jobs=-1)
grid.fit(x_train, y_train)

print("Best Alpha:", grid.best_params_)

Best Alpha: {'alpha': 0.1}

In [20]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train,y_train)

In [21]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=0.1, max_iter=5000, tol=0.0001)
lasso_reg.fit(x_train,y_train)

Lasso(alpha=0.1, max_iter=5000)

In [24]:
lasso_reg.score(x_train,y_train)

0.6827792288484937

In [22]:
lasso_reg.score(x_test,y_test)

0.1381294733950622

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [26]:
from sklearn.linear_model import Lasso

lasso_reg = Lasso(alpha=0.1, max_iter=5000)
lasso_reg.fit(x_train_scaled, y_train)

Lasso(alpha=0.1, max_iter=5000)

In [27]:
print("Train Score:", lasso_reg.score(x_train_scaled, y_train))
print("Test Score :", lasso_reg.score(x_test_scaled, y_test))

Train Score: 0.6827792288484937
Test Score : 0.1381294733950701